// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-PAK0T8vPSW-obhxPFug-wl8Vk8FzbQ4',
    appId: '1:626709433373:web:6ef05fbf0a375e6ee08af4',
    messagingSenderId: '626709433373',
    projectId: 'restaurant-app-125ea',
    authDomain: 'restaurant-app-125ea.firebaseapp.com',
    storageBucket: 'restaurant-app-125ea.appspot.com',
    measurementId: 'G-E6JS783WLX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMGN5MlDf2YqA3HG6uDGdXpDGSQQVny60',
    appId: '1:404399548475:ios:6d891f6994bb50284dd41e',
    messagingSenderId: '404399548475',
    projectId: 'restaurantwebsite-4bdd8',
    storageBucket: 'restaurantwebsite-4bdd8.firebasestorage.app',
    iosBundleId: 'com.kaistable.restaurantWebsite',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSzo86iMcwW-mjuAXgh1lQ7t9NJLZV0ro',
    appId: '1:404399548475:android:c7ef5610488496554dd41e',
    messagingSenderId: '404399548475',
    projectId: 'restaurantwebsite-4bdd8',
    storageBucket: 'restaurantwebsite-4bdd8.firebasestorage.app',
  );

}