// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-aHLAypbdgpbqlSNDl_5ofc257kKQPTI',
    appId: '1:404399548475:web:782d48d2dfe1e4604dd41e',
    messagingSenderId: '404399548475',
    projectId: 'restaurantwebsite-4bdd8',
    authDomain: 'restaurantwebsite-4bdd8.firebaseapp.com',
    storageBucket: 'restaurantwebsite-4bdd8.firebasestorage.app',
    measurementId: 'G-4ETNQB0PV4',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMGN5MlDf2YqA3HG6uDGdXpDGSQQVny60',
    appId: '1:404399548475:ios:68720a8c2ae8f4c44dd41e',
    messagingSenderId: '404399548475',
    projectId: 'restaurantwebsite-4bdd8',
    storageBucket: 'restaurantwebsite-4bdd8.firebasestorage.app',
    iosBundleId: 'com.alestra.userapp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSzo86iMcwW-mjuAXgh1lQ7t9NJLZV0ro',
    appId: '1:404399548475:android:c7ef5610488496554dd41e',
    messagingSenderId: '404399548475',
    projectId: 'restaurantwebsite-4bdd8',
    storageBucket: 'restaurantwebsite-4bdd8.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMGN5MlDf2YqA3HG6uDGdXpDGSQQVny60',
    appId: '1:404399548475:ios:3e4f91d568851a524dd41e',
    messagingSenderId: '404399548475',
    projectId: 'restaurantwebsite-4bdd8',
    storageBucket: 'restaurantwebsite-4bdd8.firebasestorage.app',
    iosBundleId: 'com.example.kaistableWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-aHLAypbdgpbqlSNDl_5ofc257kKQPTI',
    appId: '1:404399548475:web:ef4bbc8864f00d854dd41e',
    messagingSenderId: '404399548475',
    projectId: 'restaurantwebsite-4bdd8',
    authDomain: 'restaurantwebsite-4bdd8.firebaseapp.com',
    storageBucket: 'restaurantwebsite-4bdd8.firebasestorage.app',
    measurementId: 'G-GF799D5T7X',
  );

}