

class GlobalVariables
{
  List<String> losAngelesCities = [
    "Beverly Hills",
    "Santa Monica",
    "West Hollywood",
    "Downtown LA",
    "Hollywood",
    "Pasadena",
    "Long Beach",
    "Malibu",
    "Glendale",
    "Burbank",
    "Culver City",
    "Torrance",
    "Manhattan Beach",
    "Redondo Beach",
    "Hermosa Beach",
    "Inglewood",
    "Compton",
    "Carson",
    "Downey",
    "Norwalk",
    "Whittier",
    "Arcadia",
    "Monterey Park",
    "Alhambra",
    "San Gabriel",
    "Rosemead",
    "El Monte",
    "West Covina",
    "Pomona",
    "Diamond Bar",
    "Walnut",
    "La Puente",
    "Baldwin Park",
    "Industry",
    "Duarte",
    "Monrovia",
    "Sierra Madre",
    "San Marino",
    "South Pasadena",
    "La Canada Flintridge",
    "Altadena",
    "North Hollywood",
    "Studio City",
    "Sherman Oaks",
    "Encino",
    "Tarzana",
    "Woodland Hills",
    "Calabasas",
    "Agoura Hills",
    "Westlake Village",
    "Thousand Oaks",
    "Simi Valley",
    "Chatsworth",
    "Granada Hills",
    "Porter Ranch",
    "Northridge",
    "Reseda",
    "Van Nuys",
    "Panorama City",
    "Mission Hills",
    "Sylmar",
    "San Fernando",
    "Sun Valley",
    "Sunland",
    "Tujunga",
    "La Crescenta",
    "Montrose",
    "Eagle Rock",
    "Highland Park",
    "Glassell Park",
    "Atwater Village",
    "Los Feliz",
    "Silver Lake",
    "Echo Park",
    "Koreatown",
    "Mid-City",
    "West Adams",
    "Leimert Park",
    "Crenshaw",
  ];

  List<String> newYorkCitiesList = [
    "Manhattan",
    "Brooklyn",
    "Queens",
    "The Bronx",
    "Staten Island",
    "Long Island City",
    "Astoria",
    "Flushing",
    "Forest Hills",
    "Jackson Heights",
    "Sunnyside",
    "Woodside",
    "Bayside",
    "Whitestone",
    "College Point",
    "Jamaica",
    "Richmond Hill",
    "Ozone Park",
    "Howard Beach",
    "Rockaway Beach",
    "Far Rockaway",
    "Coney Island",
    "Brighton Beach",
    "Sheepshead Bay",
    "Bay Ridge",
    "Park Slope",
    "Williamsburg",
    "Greenpoint",
    "Bushwick",
    "Bedford-Stuyvesant",
    "Crown Heights",
    "Flatbush",
    "East Flatbush",
    "Brownsville",
    "East New York",
    "Sunset Park",
    "Bensonhurst",
    "Dyker Heights",
    "Midwood",
    "Gravesend",
    "Borough Park",
    "Flatlands",
    "Canarsie",
    "Mill Basin",
    "Marine Park",
    "Bergen Beach",
    "Downtown Brooklyn",
    "Brooklyn Heights",
    "DUMBO",
    "Carroll Gardens",
    "Cobble Hill",
    "Red Hook",
    "Gowanus",
    "Prospect Heights",
    "Fort Greene",
    "Clinton Hill",
    "Boerum Hill",
    "Windsor Terrace",
    "Kensington",
    "Ditmas Park",
    "Prospect Lefferts Gardens",
    "New Lots",
    "Spring Creek",
    "City Island",
    "Riverdale",
    "Kingsbridge",
    "Fordham",
    "University Heights",
    "Morris Heights",
    "Mount Eden",
    "Highbridge",
    "Concourse",
    "Mott Haven",
    "Melrose",
    "Hunts Point",
    "Longwood",
    "Morrisania",
    "Crotona Park East",
    "East Tremont",
  ];
 
}